import './globals.css';
import { routes } from './[docpage]/page';

export const metadata = {
	title: 'JOSN Docs',
	description: 'Generated by create next app',
};

export default function RootLayout ({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="flex">
				<nav className="w-1/4 max-w-xs bg-slate-300">
					<section>
						<ul className="py-4 px-3 space-y-1">
							{routes.map((route, k) => <li key={k}>
								<a href="" className="font-bold">{route.title}</a>
							</li>)}
						</ul>
					</section>
				</nav>
				<main className="grow">{children}</main>
			</body>
		</html>
	);
}
