import { Source_Sans_Pro } from 'next/font/google';

import './globals.css';

const source_Sans_Pro = Source_Sans_Pro({
	weight: ['400', '700'],
	subsets: ['latin'],
	display: 'swap',
});

export const metadata = {
	title: 'JOSN Docs',
	description: 'Generated by create next app',
};

export default function RootLayout ({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={source_Sans_Pro.className}>{children}</body>
		</html>
	);
}
